"""empty message

Revision ID: 417cd139459e
Revises: 4bdffdb7118c
Create Date: 2018-01-02 12:28:48.314517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417cd139459e'
down_revision = '4bdffdb7118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret')
    # ### end Alembic commands ###
