"""empty message

Revision ID: 4bdffdb7118c
Revises: cef2e600cb78
Create Date: 2017-12-20 15:19:12.613944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdffdb7118c'
down_revision = 'cef2e600cb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###
